package generator.probes;

import core.BaseSequence;
import generator.SeqGenerator;
import utils.LSH;

public class ProbesGeneratorLSH implements SeqGenerator {

    private final float minDist;
    private final SeqGenerator generator;
    private final LSH lsh;
    private final int k;

    /**
     * Creates a Probes' generator object that utilizes LSH for Jaccard distance checks.
     * @param generator a generator that generates BaseSequence objects. This generator should fulfill basic DNA constrains such as GC content requirements, no homopolymers, etc.
     * @param lsh the LSH instance used for distance checks.
     * @param minDist the minimum distance required for the DNA sequences generated by this instance.
     */
    public ProbesGeneratorLSH(SeqGenerator generator, LSH lsh, float minDist) {
        this.generator = generator;
        this.minDist = minDist;
        this.lsh = lsh;
        this.k = lsh.getK();
    }

    /**
     * Attempts to add a given DNA sequence to the LSH. If the distance requirements are not met, this function returns false.
     * @param seq the examined BaseSequence.
     * @return true, if seq meets the requirements.
     */
    private synchronized boolean tryAdd(BaseSequence seq) {
        if (lsh.similarSeqs(seq).stream().map(can -> can.jaccardDistance(seq, k)).min(Float::compare).orElse(1.0f) >= minDist) {
            lsh.insert(seq);
            return true;
        }

        return false;
    }

    /**
     * @return a BaseSequence satisfying the given constraints.
     */
    @Override
    public BaseSequence generate() {
        return generator.stream().filter(this::tryAdd).findFirst().orElseThrow();
    }
}
